### ISSUE TITLE
Subtle: Alignment

### ISSUE THREAD

**Issue by blerude** [christinahauri/prj-rev-bwfs-dasmoto#1]
https://github.com/christinahauri/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L10-L15

Careful how you structure your divs here. It should look like this, with the child elements indented one level from the parent, and the opening and closing tags matching up: 

```
<div class="item">
    <h2 id="brush">Brushes</h2>
    <img src="https://s3.amazonaws.com...">
    <h3>Hacksaw Brushes</h3>
    <p>Made of the highest quality oak...<span class="price">Starting at $3.00 / brush.</span></p>
</div>
```

**Comment by christinahauri** [comment]
Great example; thank you for the visual!
