### ISSUE TITLE
Important: Readability

### ISSUE THREAD

**Issue by blerude** [christinahauri/prj-rev-bwfs-dasmoto#3]
https://github.com/christinahauri/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css#L1-L7

Again, think about how easy your code is to read. Try formatting each selector + styling like this: 

```
.item h2 {
     font-size: 32px;
     font-weight:bold; 
     color:white;
}
```

Subtle difference, but that's the common practiced way to do things and looks cleaner.

**Comment by christinahauri** [comment]
Thank you! :)
