### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [christinahauri/prj-rev-bwfs-dasmoto#4]
Grade: Meets Expectations

Awesome job on this project! Your code successfully includes all the necessary elements and you're getting a great hang of the core techniques of HTML and CSS coding. You're perfectly applying classes and ids and creating your CSS selectors.

Moving forward, think about the readability of your code more. While it might seem less important than the actual code itself, writing great yet disorganized code undermines your work by discouraging collaborators from reading it. It also causes headaches for you as your projects grow in size and complexity! Take note of the suggestions I left you on how to format more effectively. Finally, CSS can be really fun because you can take it so many different places. I recommend Google Fonts for finding a wide array of more exciting fonts to use, and Coolors.co for generating aesthetic color palettes to bring your apps to life. I hope you have playing with those resources! Again, awesome job!

**Comment by christinahauri** [comment]
Awesome feedback; this is very helpful - I appreciate it!
